[package]
name = "veda-report"
version = "0.0.1"
compiler = "0.14.2"
entrypoint = "lib.typ"
repository = "https://github.com/Vedabahu/veda-report"
authors = ["Vedabahu <79869936+Vedabahu@users.noreply.github.com>"]
license = "MIT-0"
description = "A template with generous spacing for reports, assignments, course documents, and similar (shorter) documents."
keywords = ["notes", "report", "non-fiction", "class", "lecture"]
categories = ["report"]
exclude = ["example.*"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
